# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('party', models.CharField(choices=[('republican', 'Republican'), ('democratic', 'Democratic'), ('independent', 'Independent')], max_length=25)),
                ('photo_url', models.URLField()),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
